dist: xenial

language: python

cache: pip

branches:
  only:
    - master

# existing Python versions
python:
  - 3.6
  - 3.7

# command to install dependencies
install:
  - python -m pip install pipenv
  - pipenv --python 3
  - pipenv install --dev

# command to run tests, run all tests only in nightly build
script:
  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then pipenv run pytest -m "not custom"; else pipenv run pytest -m lite; fi
